Exercise 1: Introduction to Data Analysis (Easy)

In [ ]:
# Exercise 2: Dataset Loading and Initial Analysis
import pandas as pd

df1 = pd.read_csv('Time_Americans_Spend_Sleeping.csv')
print('1st dataset:')
print(df1.head())
#  This dataset contains information about sleep habits and sleep duration among Americans over the years. Typical variables include:
# - Year
# - Average hours of sleep
# - people info : age, gender


df2 = pd.read_csv('Mental_health_Depression_disorder_Data.csv',  low_memory=False)
print('2nd dataset:')
print(df2.head())
# This dataset contains prevalence rates of several mental health disorders across countries and years. Disorders commonly included are:
# Schizophrenia
# Anxiety disorders
# Bipolar disorder
# Eating disorders
# Drug use disorders

df3 = pd.read_csv('clean_dataset.csv')
print('3rd dataset:')
print(df3.head(3))
df3.info()
# This dataset is a cleaned version of the classic UCI Credit Card Approval dataset. It contains applicant information used to determine whether a credit card application is approved or rejected.
# Typical features include:
# Age
# Income
# Employment status
# Marital status
# Credit history indicators
# Other financial attributes

1st dataset:
   index  Year  Period  Avg hrs per day sleeping  Standard Error Type of Days  \
0      0  2003  Annual                      8.57           0.018     All days
1      1  2004  Annual                      8.55           0.026     All days
2      2  2005  Annual                      8.62           0.023     All days
3      3  2006  Annual                      8.63           0.024     All days
4      4  2007  Annual                      8.57           0.024     All days

           Age Group  Activity   Sex
0  15 years and over  Sleeping  Both
1  15 years and over  Sleeping  Both
2  15 years and over  Sleeping  Both
3  15 years and over  Sleeping  Both
4  15 years and over  Sleeping  Both
2nd dataset:
   index       Entity Code  Year Schizophrenia (%) Bipolar disorder (%)  \
0      0  Afghanistan  AFG  1990           0.16056             0.697779
1      1  Afghanistan  AFG  1991          0.160312             0.697961
2      2  Afghanistan  AFG  1992          0.160135             0.698107
3      3  Afghanistan  AFG  1993          0.160037             0.698257
4      4  Afghanistan  AFG  1994          0.160022             0.698469

  Eating disorders (%)  Anxiety disorders (%)  Drug use disorders (%)  \
0             0.101855               4.828830                1.677082
1             0.099313               4.829740                1.684746
2             0.096692               4.831108                1.694334
3             0.094336               4.830864                1.705320
4             0.092439               4.829423                1.716069

   Depression (%)  Alcohol use disorders (%)
0        4.071831                   0.672404
1        4.079531                   0.671768
2        4.088358                   0.670644
3        4.096190                   0.669738
4        4.099582                   0.669260
3rd dataset:
   Gender    Age  Debt  Married  BankCustomer     Industry Ethnicity  \
0       1  30.83  0.00        1             1  Industrials     White
1       0  58.67  4.46        1             1    Materials     Black
2       0  24.50  0.50        1             1    Materials     Black

   YearsEmployed  PriorDefault  Employed  CreditScore  DriversLicense  \
0           1.25             1         1            1               0
1           3.04             1         1            6               0
2           1.50             1         0            0               0

   Citizen  ZipCode  Income  Approved
0  ByBirth      202       0         1
1  ByBirth       43     560         1
2  ByBirth      280     824         1
<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    str
 6   Ethnicity       690 non-null    str
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    str
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), str(3)
memory usage: 86.4 KB

🌟Exercise 3: Identifying Data Types

Time_Americans_Spend_Sleeping dataset:
Quantitative: Year   Avg_hrs_per_day_sleeping  Standard_Error 
Qualitative:  Period Type_of_Days Age_group Activity Sex
Reason: 
Anything measured numerically is quantitative.
Anything describing a group or category is qualitative.

Mental_health_Depression_disorder_Data dataset: 
Quantitative: Year, Schizophrenia %, Bipolar disorder (%) Eating disorders (%)  Anxiety disorders (%)  Drug use disorders (%)
Qualitative:  Entity, Code
Reason: same as above

In [ ]:
# 🌟Exercise 4: Exploring Data Types
iris_df = pd.read_csv('Iris.csv')
iris_df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

Quantitative: SepalLengthCm	SepalWidthCm	PetalLengthCm	PetalWidthCm . Because they are numeric and represent some type of measurements
Qualitative:  Id, Species. Because they represent labels or descriptions or categories that can't be measured or calculated

🌟Exercise 5: Basic Observation Skills in Data Analysis


interesting columns: 
Year
Avg hrs per day sleeping
Standard Error
age group
Type of Days

can be useful for analysis topic like:  do young people sleep more than older people over the years and do people sleep more over the years in general?
Reason: we have average hours of sleeping per day data  for different age groups for the same year and different years, we can check on the same years, if younger people sleep more, and also over the years, we can check if there's an increase or decrease on sleeping hours for the same age group.

🌟 Exercise 6: Identifying Data Types
Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file. -- structured
Photographs uploaded to a social media platform.  -- unstructured
A collection of news articles on a website. -- unstructured
Inventory data in a relational database. -- structured
Recorded interviews from a market research study. -- unstructured

🌟 Exercise 7: Transformation Exercise
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
we can structure blogs data as following: country / location, date of visit, days of traveling, cities list , activities, attraction places, restaurants lists, etc.. store them into a table, rating(1-10)
Reason: 
Blog posts are free text, but they often contain repeated patterns: place names, experiences, opinions, rating, etc..


Audio recordings of customer service calls.
convert audio to text, extract keywords, categorize questions or topics and structure them into : Issues, Resolution, duration, satisfaction score
Audio itself is not directly analyzable, but once converted to text, we can extra patterns and information

Handwritten notes from a brainstorming session.
scanning the notes and extra texts through image extraction or (Optical Character Recognition) , once we get text, we can extract data again like: name of the person, keywords, theme, ideas
Brainstorming notes are: messy fragmented unordered . But they usually contain: ideas, tasks, themes

A video tutorial on cooking.
Extract audio → speech-to-text (recipe narration), Extract key frames (images of steps), Combine into structured recipe steps, then we can organize data into: steps, ingredients, duration, cooking tools needed, etc..
The video contains multi data types, audio, images, timing, By combining these, we can convert the video into a step-by-step recipe dataset.

🌟 Exercise 8 : Import a file from Kaggle
https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/train.zip

In [52]:

url = 'https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/train.zip'
train_df = pd.read_csv(url)
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
# 🌟 Exercise 9 : Export a dataframe to excel format and JSON format.
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London']
}

df = pd.DataFrame(data)
df.head()
df.to_excel('my_data.xlsx', index=False)
df.to_json('my_data.json', indent=4, orient="records")

In [ ]:
#🌟 Exercise 10: Reading JSON Data
url = 'https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/posts.zip'
posts_df = pd.read_json(url)
posts_df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...